POST http://localhost:8080/users/all HTTP/1.1
content-type: application/json

{
    "requestor": {
        "name": "admin",
        "password": "password"
    }
}

###

POST http://localhost:8080/users/login/ HTTP/1.1
content-type: application/json

{
    "name": "KarlHeinz",
    "password": "test12346"
}

###

GET http://localhost:8080/users/mail

###

POST http://localhost:8080/users/new HTTP/1.1
content-type: application/json

{
    "requestor": {
        "name": "admin",
        "password": "password"
    },
    "name": "admin2",
    "email": "admin2@bigboss.de",
    "password": "password",
    "permitionId": 1
}

###

POST http://localhost:8080/users/login HTTP/1.1
content-type: application/json

{
    "name": "KarlHeinz",
    "password": "test12345"
}

###

DELETE http://localhost:8080/users/delete HTTP/1.1
content-type: application/json

{
    "requestor": {
        "name": "KarlHeinz",
        "password": "test12345"
    },
    "id": 10
}

###

POST http://localhost:8080/entries/all HTTP/1.1
content-type: application/json

{
    "requestor": {
        "name": "KarlHeinz",
        "password": "test12345"
    }
}

###


POST https://perfume-sally-ran-layer.trycloudflare.com/entries/all HTTP/1.1
content-type: application/json

{
    "requestor": {
        "name": "KarlHeinz",
        "password": "test12345"
    }
}

###

POST http://localhost:8080/entries/new HTTP/1.1
content-type: application/json

{
    "requestor": {
        "name": "KarlHeinz",
        "password": "test12345"
    },
    "suspect": "Klaus Mirk",
    "school": "Wigbertschule",
    "class": "10z",
    "time": "2022-01-04T23:55:26.111Z",
    "location": "an der Schule",
    "incident": "hat mein Frühstück geklaut",
    "authorId": 11
}

###

DELETE http://localhost:8080/entries/delete HTTP/1.1
content-type: application/json

{
    "requestor": {
        "name": "KarlHeinz",
        "password": "test12345"
    },
    "id": 24
}