GET http://localhost:8080/users/all

###

GET http://localhost:8080/users/password/f

###

GET http://localhost:8080/users/mail

###

POST http://localhost:8080/users/new HTTP/1.1
content-type: application/json

{
    "name": "KarlHeinz",
    "email": "Karl@Heinz.de",
    "password": "test12345"
}

###

DELETE http://localhost:8080/users/delete HTTP/1.1
content-type: application/json

{
    "id": 9
}

###

GET http://localhost:8080/entries/all

###

POST http://localhost:8080/entries/new HTTP/1.1
content-type: application/json

{
    "title": "Wer das ließt, der ist blöd",
    "authorId": 10
}

###

DELETE http://localhost:8080/entries/delete HTTP/1.1
content-type: application/json

{
    "id": 1,
    "userId": 8
}